project_id = "vkkmfttatyluagmxgcci"

[functions.check-authenticity]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.score-story]
verify_jwt = false

[functions.send-recap-email]
verify_jwt = false